README.md

add colab example

---

aspen/LoraLiner.py
aspen/__init__.py
aspen/model.py
aspen/model_chatglm.py
aspen/model_llama.py
aspen/modelargs.py
aspen/utils.py
mlora.py
tests/dispatcher_test.py

* TODO: implement the chatglm2 train

feature: add abstract interface for llama and chatglm

---

aspen/LoraLiner.py
aspen/dispatcher.py
aspen/model.py
aspen/model_chatglm.py
aspen/model_llama.py
aspen/modelargs.py
mlora.py

1. add inference mode just for test model code, due to the performance.
2. bug fixed: llama2 model
3. can disable lora for model test

features: lora module can load from file

---

aspen/__init__.py
aspen/model.py
aspen/model_chatglm.py
aspen/tokenizer.py
mlora.py

* TODO: lora train in chatglm2-6b maybe need different way with llama

 feature: chatglm2-6b in float16 can get the same behaviour

---

aspen/LoraLiner.py
aspen/model.py
aspen/model_chatglm.py
aspen/model_llama.py
aspen/utils.py

bug fixed: disable the grad without bitsandbytes

feature: add the chatglm lora weight save to local

---

aspen/model.py
aspen/model_chatglm.py
requirements.txt

see: https://github.com/THUDM/ChatGLM2-6B/issues/163

feature: support chatglm2-6b qlora

---

inference.py
mlora/generate.py

Now m-LoRA can inference better

feature: support repetition penalty and logit normalization to the inference

---

.github/workflows/pre-commit
.github/workflows/python-test-dev.yml
mlora/model_llama.py
mlora/modelargs.py

feature: add lizard to check the cyclomatic complexity

---

mlora/common.py
mlora/model/model_llama.py

How to use: nsys profile -w true -t cuda,nvtx -s none -o test_report -f true -x true python mlora.py xxx
we can get the nsys-report file, and then use the nsight system to analyze it, like below

feature: a example of profiler function

---

.github/workflows/run_on_dev.yml
tests/pipeline_example.py
tests/pipeline_example_check.py
tests/transport_check.py

here is the test list:
- transport test
- pipeline example test

test: add pipline related test

---

mlora/config.py
mlora/model/RMSNorm.py

bug fixed: init the config

---

.github/workflows/ci_script.py
README.md
mlora/config.py
mlora/model/RMSNorm.py
mlora/model/model_llama.py
mlora/model/modelargs.py
mlora/trainer/trainer.py
mlora/utils.py
pyproject.toml
requirements.txt

add unmatched base model check
update transformers version
update README
add safety check to models with sliding window attention
fix wrong condition
bug fixed: init the config
* rmsnorm redundant code
add comment and make code clean

Adding support for Qwen2(通义千问) and Mistral

---

mlora/model/model_llama.py

fix
```
"multi-lora-fine-tune/mlora/model/model_llama.py", line 32, in __init__
self.lm_head_.weight.copy_(weight)
NotImplementedError: Cannot copy out of meta tensor; no data!
```

bug fixed: fix model offload bug

---

benchmarks/bench_peft.py
mlora.py
mlora/__init__.py
mlora/checkpoint/recompute.py
mlora/common.py
mlora/model/LoraLiner.py
mlora/model/RMSNorm.py
mlora/model/model_llama.py
mlora/pipeline/pipe.py
mlora/profiler/profiler.py
mlora/profiler/traceviz.py
mlora/trainer/trainer.py
mlora/utils.py

1. Use [cuda nvtx](https://developer.nvidia.com/blog/cuda-pro-tip-generate-custom-application-profile-timelines-nvtx/) to profile the mlora's performance.
2. Use Pytorch's `autograd` framework to get the execution graphs and traces.
1. Add the `--trace` argument to enable the trace mode.
2. Use `nsys` to profile.
Your command like this: `nsys profile -w true -t cuda,nvtx -s none -o test_report -f true -x true python mlora.py --base_model /data/Llama-2-7b-hf/ --load_8bit --device "cuda:0" --config ./config/dummy.json --trace`
3. Use `NVIDIA Nsight Systems` to analyze the profile file (I will later provide a CLI version to automatically generate some important summaries.).
NOTE: only use this for debugging, so you need to add the function by yourself, (I prefer to add the function in …

feature: add the profiler

---

demo/cpo/cpo_case_1.yaml
demo/dpo/dpo_case_1.yaml
demo/dpo/dpo_case_2.yaml
demo/dpo/dpo_case_3.yaml
demo/lora/lora_case_1.yaml
demo/loraplus/loraplus_case_1.yaml
demo/preference_prompt.yaml
demo/preference_template.json
demo/prompt.yaml
demo/template.json
mlora/cli/dataset.py
mlora/cli/file.py
mlora/config/dataset.py
mlora/executor/context/__init__.py
mlora/executor/task/cpo_task.py
mlora/executor/task/dpo_task.py
mlora/executor/task/task.py
mlora/executor/task/train_task.py
mlora/prompter/__init__.py
mlora/prompter/instruction_data_prompter.py
mlora/prompter/preference_data_prompter.py
mlora/prompter/prompter.py
mlora/server/__init__.py
mlora/server/adapter.py
mlora/server/dataset.py
mlora/server/file.py
mlora/server/storage.py
mlora/server/task.py
mlora_server.py

* use the jinja language to generate prompt
* add a new command to verify if the prompt is correct, like below:

[improvment] add user friendly method to generate the prompt

---

mlora/executor/task/task.py

fix the key error data["train"] to data["data_points"]

bug fix: key error in task.py

---

README.md
demo/vera/vera_case_1.yaml
docs/develop_new_adapter.md
mlora/config/__init__.py
mlora/config/adapter.py
mlora/executor/context/__init__.py
mlora/executor/context/lora.py
mlora/executor/context/train.py
mlora/executor/context/vera.py
mlora/model/modules/__init__.py
mlora/model/modules/linear.py
mlora/model/modules/vera.py
mlora_cli/adapter.py
pyproject.cli.toml
tests/finetune_all_case.sh

VeRA does not perform well on the small model, possibly due to insufficient parameters.

[feature] VeRA adapter support, and add document "how to develop new adapter"

---

mlora/executor/executor.py
mlora/executor/task/cpo_task.py
mlora/executor/task/dpo_task.py
mlora/executor/task/train_task.py
mlora/model/args.py
mlora/profiler/__init__.py
mlora/profiler/metric.py
mlora/utils/__init__.py
mlora/utils/cmd.py
mlora/utils/setup.py
mlora_server.py
mlora_train.py
pyproject.mlora.toml

like below, we can easily compare different adaptes' loss

[feature] add a profiler to collect metric, loss and memory cost

---

mlora/model/tokenizer/tokenizer.py

[bug fix] Tokenizer 

---

pyproject.mlora.toml

I add the python-multipart dependency that the server need

upload the mlora server dependency

---

tests/pipeline_example.py

modify the wrong dependency in mLoRA/tests/pipeline_example.py

modify the wrong dependency 
